/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Code;

import javax.swing.JOptionPane;

/**
 *
 * @author Junaidi
 */
public class PossibleTicket extends javax.swing.JPanel {
    DataPemesan dp;
    /**
     * Creates new form PossibleTicket
     * @param 
     */
    String waktu_awal;
    String waktu_tiba;
    String harga;
    String jenis;
    public PossibleTicket(String waktu_awal, String waktu_tiba, String harga, String jenis, DataPemesan dp) {
        this.dp = dp;
        this.waktu_awal = waktu_awal;
        this.waktu_tiba = waktu_tiba;
        this.harga = harga;
        this.jenis = jenis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        waktuAwal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        waktuAkhir = new javax.swing.JLabel();
        t_harga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaPesawat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setMaximumSize(new java.awt.Dimension(340, 110));
        setPreferredSize(new java.awt.Dimension(350, 150));

        waktuAwal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        waktuAwal.setText(waktu_tiba);

        jLabel5.setText("-");

        waktuAkhir.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        waktuAkhir.setText(waktu_tiba);

        t_harga.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        t_harga.setText(harga);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Rp");

        namaPesawat.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaPesawat.setText(jenis);

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Pilih");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waktuAwal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waktuAkhir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(namaPesawat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_harga)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waktuAwal)
                            .addComponent(waktuAkhir)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(t_harga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPesawat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dp.setHarga(t_harga.getText());
        dp.setWaktu_awal(waktuAwal.getText());
        dp.setWaktu_akhir(waktuAkhir.getText());
        dp.setJ_pesawat(namaPesawat.getText());
        Konfirmasi konf = new Konfirmasi(dp);
        konf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel namaPesawat;
    private javax.swing.JLabel t_harga;
    private javax.swing.JLabel waktuAkhir;
    private javax.swing.JLabel waktuAwal;
    // End of variables declaration//GEN-END:variables
}
